<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.11.0" xml:lang="en-US">
  <compounddef id="classgyp_1_1common_1_1_cycle_error" kind="class" language="Python" prot="public">
    <compoundname>gyp::common::CycleError</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classgyp_1_1common_1_1_cycle_error_1a2e607a3af0c61a217a1ad7134e8417b2" prot="public" static="no" mutable="no">
        <type></type>
        <definition>gyp.common.CycleError::nodes</definition>
        <argsstring></argsstring>
        <name>nodes</name>
        <qualifiedname>gyp.common.CycleError.nodes</qualifiedname>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" line="583" column="1" bodyfile="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" bodystart="583" bodyend="-1"/>
        <referencedby refid="classgyp_1_1common_1_1_cycle_error_1a47df8e5d1c23a686e5fd9abdfb9414ac" compoundref="common_8py" startline="585" endline="588">gyp.common.CycleError.__str__</referencedby>
        <referencedby refid="classgyp_1_1input__test_1_1_test_find_cycles_1a47d3bca86eee0695a11311b9c9413b4a" compoundref="input__test_8py" startline="75" endline="96">gyp.input_test.TestFindCycles.test_big_cycle</referencedby>
        <referencedby refid="classgyp_1_1input__test_1_1_test_find_cycles_1afb0bc932adc24f7c7421661cd75c90bc" compoundref="input__test_8py" startline="43" endline="49">gyp.input_test.TestFindCycles.test_cycle_self_reference</referencedby>
        <referencedby refid="classgyp_1_1input__test_1_1_test_find_cycles_1ac50c16699e29887917ec4a006ce77d87" compoundref="input__test_8py" startline="50" endline="62">gyp.input_test.TestFindCycles.test_cycle_two_nodes</referencedby>
        <referencedby refid="classgyp_1_1input__test_1_1_test_find_cycles_1a3fdcac54c3a4d7469b0b81f38a4c737c" compoundref="input__test_8py" startline="35" endline="42">gyp.input_test.TestFindCycles.test_no_cycle_dag</referencedby>
        <referencedby refid="classgyp_1_1input__test_1_1_test_find_cycles_1a7229bd5cfeea0fa702dbb67372ce66bb" compoundref="input__test_8py" startline="23" endline="26">gyp.input_test.TestFindCycles.test_no_cycle_empty_graph</referencedby>
        <referencedby refid="classgyp_1_1input__test_1_1_test_find_cycles_1ad3671abfe4099eb2a0253ee024d6ab6b" compoundref="input__test_8py" startline="27" endline="34">gyp.input_test.TestFindCycles.test_no_cycle_line</referencedby>
        <referencedby refid="classgyp_1_1input__test_1_1_test_find_cycles_1a4080a6b31c2f2dd5d3234b12946028da" compoundref="input__test_8py" startline="63" endline="74">gyp.input_test.TestFindCycles.test_two_cycles</referencedby>
      </memberdef>
    </sectiondef>
    <sectiondef kind="public-func">
      <memberdef kind="function" id="classgyp_1_1common_1_1_cycle_error_1a66ab1348fb6fadccfafa130d43b44c9b" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>gyp.common.CycleError.__init__</definition>
        <argsstring>(self, nodes)</argsstring>
        <name>__init__</name>
        <qualifiedname>gyp.common.CycleError.__init__</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type><ref refid="classgyp_1_1common_1_1_cycle_error_1a2e607a3af0c61a217a1ad7134e8417b2" kindref="member">nodes</ref></type>
          <defname>nodes</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" line="582" column="1" bodyfile="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" bodystart="582" bodyend="584"/>
      </memberdef>
      <memberdef kind="function" id="classgyp_1_1common_1_1_cycle_error_1a47df8e5d1c23a686e5fd9abdfb9414ac" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>gyp.common.CycleError.__str__</definition>
        <argsstring>(self)</argsstring>
        <name>__str__</name>
        <qualifiedname>gyp.common.CycleError.__str__</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" line="585" column="1" bodyfile="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" bodystart="585" bodyend="588"/>
        <references refid="classgyp_1_1common_1_1_cycle_error_1a2e607a3af0c61a217a1ad7134e8417b2" compoundref="common_8py" startline="583">gyp.common.CycleError.nodes</references>
        <references refid="classgyp_1_1input__test_1_1_test_find_cycles_1ade193367a3e2d1d756fd65715962f9a3" compoundref="input__test_8py" startline="15">gyp.input_test.TestFindCycles.nodes</references>
      </memberdef>
    </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>An exception raised when an unexpected cycle is detected.</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>gyp.common.CycleError</label>
        <link refid="classgyp_1_1common_1_1_cycle_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>gyp.common.CycleError</label>
        <link refid="classgyp_1_1common_1_1_cycle_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" line="579" column="1" bodyfile="backend/node_modules/node-gyp/gyp/pylib/gyp/common.py" bodystart="579" bodyend="588"/>
    <listofallmembers>
      <member refid="classgyp_1_1common_1_1_cycle_error_1a66ab1348fb6fadccfafa130d43b44c9b" prot="public" virt="non-virtual"><scope>gyp::common::CycleError</scope><name>__init__</name></member>
      <member refid="classgyp_1_1common_1_1_cycle_error_1a47df8e5d1c23a686e5fd9abdfb9414ac" prot="public" virt="non-virtual"><scope>gyp::common::CycleError</scope><name>__str__</name></member>
      <member refid="classgyp_1_1common_1_1_cycle_error_1a2e607a3af0c61a217a1ad7134e8417b2" prot="public" virt="non-virtual"><scope>gyp::common::CycleError</scope><name>nodes</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
